apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-demo
  name: nginx
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: nginx-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-demo
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101 # user nginx
      containers:
      - image: eugnebelskyi/nginx-joynnginx-joyn:latest
        imagePullPolicy: Always
        name: nginx-joynnginx-joyn
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-service
spec:
  selector:
   app: nginx-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
